add_lunch_combo jos_gemini-userdebug
add_lunch_combo jos_gemini-user
add_lunch_combo jos_herolte-userdebug
add_lunch_combo jos_herolte_user
add_lunch_combo jos_hero2lte-userdebug
add_lunch_combo jos_hero2lte-user
add_lunch_combo jos_oneplus3-userdebug
add_lunch_combo jos_oneplus3-user
